name: Build Images

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 */12 * * *'

jobs:
  build-deploy:
    name: "from repo/${{ matrix.repo }} as tag/${{ matrix.tag }}"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        tag: ['latest', '19.08', '19.04', 'master']
        include:
        - tag: 'latest'
          repo: 'release'
        - tag: '19.08'
          repo: '1908'
        - tag: '19.04'
          repo: '1904'
        - tag: 'master'
          repo: 'master'

    steps:
    - uses: actions/checkout@v1

    - name: Build
      env:
        DOCKER_REPO: ligato/vpp-base
        REPO: ${{ matrix.repo }}
        TAG: ${{ matrix.tag }}
      run: |
        make build
        docker run --rm "$DOCKER_REPO:$TAG" dpkg-query -f '${Version}' -W vpp

    - name: Deploy
      env:
        DOCKER_REPO: ligato/vpp-base
        REPO: ${{ matrix.repo }}
        TAG: ${{ matrix.tag }}
      run: |
        env | sort
        docker images "$DOCKER_REPO"
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        make push
